import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Sidebar from "../components/sidebar";
import Actiontrig from "../components/trigactn";
import Details from "@/components/details";
import Link from "next/link";


export default function Home() {
  const [navbar, setNavbar] = useState(false);
  return (
    <div className="bg-[#37306B]">
      <Head>
        <title>BlockIoT-New Applet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="Logo.svg" />
      </Head>

      {/* navbar start */}
      {/* <div>
        {" "}
        <NavBar />{" "}
      </div> */}
      <div>
       
        <Sidebar />{" "}
      </div>
      
      {/* nav bar end */}

      <main>
        
        <Details/>
      </main>
      

      {/* <Footer /> */}
    </div>
  );
}
