import Head from "next/head";
import { useEffect, useState } from "react";
import NavBar2 from "@/components/navbar2";
import Bulb from '../components/bulb';
import NftDetails from '../components/nftDetails';
import Footer from "@/components/footer";

export default function Home() {
  // console.log("entred home");
  const [eventDetail, setEventDetail] = useState(null);
  const [pagedata, setPageData] = useState(null);

  useEffect(() => {
    // Function to parse URL parameters
    console.log("useEffect is running 1");
    const getParameterByName = (name, url) => {
      if (!url) url = window.location.href;
      name = name.replace(/[[]]/g, '\\$&');
      const regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
        results = regex.exec(url);
      if (!results) return null;
      if (!results[2]) return '';
      return decodeURIComponent(results[2].replace(/\+/g, ' '));
    };

    // Get the event ID from the URL
    const eventId = getParameterByName('id');

    // Fetch event details based on the eventId
    const fetchEventDetails = async () => {
      try {
        // Replace the following API URL with your actual API endpoint
        const apiUrl = `api/events?id=${eventId}`;
        const response = await fetch(apiUrl);
        const data = await response.json();
        console.log("data", data);
        //   setEventDetail(data);
      } catch (error) {
        console.error('Error fetching event details:', error);
      }
    };

    const fetchData = async () => {
      try {
        const response = await fetch(`api/eventsbyid?id=${eventId}`);
        const data1 = await response.json();
        console.log("Json Data:", data1.documents[0]);
        setPageData(data1.documents[0]);
      } catch (error) {
        console.error('Error fetching data:', error);
      }
    };

    fetchData();/// funct to call for 


    if (eventId) {
      console.log("Event ID:", eventId);

      //fetchEventDetails();
    }
  }, []); // Run this effect only once on page load

  const devname = pagedata?.appletName ?? 'N/A';
  const devdesc = pagedata?.appletDescription ?? 'N/A';
  const nftname = pagedata?.appletDescription ?? 'N/A';
  const nfturl = "https://i.ibb.co/kMxfN25/vmcopy.jpg";


  return (
    <div className="bg-black">
      <Head>
        <title>BlockIoT-Execution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="vercel.svg" />
      </Head>

      <NavBar2 />

      <div className="md:mx-0 mx-7">
        {pagedata && (

          <div>
            <Bulb
              deviceDescription={devdesc}
              devicName={devname} />
          </div>
        )}


        <div className='mt-20'>
          {/* Pass eventDetail as a prop to NftDetails component */}
          {pagedata && (
            <NftDetails
              nftName={nftname}
              nftUrl={nfturl}
              eventDetail={eventDetail}
            />
          )}

        </div>
      </div>

      <div>
        <Footer />
      </div>
    </div>
  );
}
