import Loader from "@/components/loader";
import Head from "next/head";
import Sidebar from "../components/sidebar";
import NavBar from "@/components/navbar";

export default function Qrpage(){
    return(
    <div>
      <Head>
        <title>BlockIoT-New Applet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="Logo.svg" />
      </Head>

      <body className="flex flex-col h-screen">
        <div className="">
          <NavBar />
        </div>

        {/* <div>
          <Sidebar />
        </div> */}
        <div className="main-body grow flex justify-center">
          <Loader/> 
        </div>

      </body>

      {/* <Footer /> */}
    </div>
  );


}